# Generated by Django 4.1.7 on 2023-03-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('user', 'content', 'timestamp'), name='unique_message'),
        ),
    ]
