# Generated by Django 4.1.7 on 2023-03-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_unique_message'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='unique_message',
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('user', 'timestamp'), name='unique_message'),
        ),
    ]
